import Head from 'next/head'
import Image from 'next/image'
import Menu from '../components/menu'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import Pinned from '../components/pinned'
import Bloglist from '../components/bloglist'
import Article from '../components/article'

const client = new GraphQLClient("https://api-ap-northeast-1.hygraph.com/v2/cl6lsx6ia0y7l01ulhpjshdti/master")
const QUERY = gql`{
  posts {
    id
    title
    datePublished
    category
    description
    content {
      html
    }
    time
    author {
      name
      avatar {
        url
      }
    }
    coverImg {
      url
    }
  }
}
`

export async function getStaticProps () {
  const { posts } = await client.request(QUERY)
  return {
    props: {
      posts
    },
    revalidate: 10,
  }
}

export default function Home ({ posts }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="blog">
        <Menu />
        <Pinned />
        <Bloglist posts={posts} />
        <Article />
      </div>
    </div>
  )
}
